// <auto-generated />
using System;
using HartInterCivic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HartInterCivic.Migrations
{
    [DbContext(typeof(HartInterCivicDbContext))]
    partial class HartInterCivicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HartInterCivic.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item", "HartInterCivic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            Description = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Count = 2,
                            Description = "Mouse"
                        });
                });

            modelBuilder.Entity("HartInterCivic.Models.TimerConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoStart")
                        .HasColumnType("bit");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TimerConfiguration", "HartInterCivic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoStart = true,
                            Interval = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
